# Refer to the official Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for GitHub Actions
  # See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # doing weekly because Sunil prefers doing the updates in bulk

  # Configuration for Go modules
  # See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    update-types:
      - "minor"
      - "patch"
    # the major updates are probably going to break code and therefore best left to manual updates
